### ISSUE TITLE
Error rendering ifc sample

### ISSUE THREAD

**Issue by ehtick** [xBimTeam/XbimGeometry#242]
This example will crash the creation of geometry.

[BeamUnitTestsVaryingPath.zip](https://github.com/xBimTeam/XbimGeometry/files/4091634/BeamUnitTestsVaryingPath.zip)

**Comment by andyward** [comment]
This is the error from the logs:

```
Processing failure
Only 3D Directions are supported for normalised at present
   at Xbim.Ifc4.GeometryResource.IfcDirection.Normalise()
   at Xbim.Geometry.XbimSolid.Init(IIfcRevolvedAreaSolid solid, IIfcProfileDef overrideProfileDef, ILogger logger)
   at Xbim.Geometry.XbimSolid.Init(IIfcSweptAreaSolid solid, IIfcProfileDef overrideProfileDef, ILogger logger)
   at Xbim.Geometry.XbimSolid.Init(IIfcSolidModel solid, ILogger logger)
   at Xbim.Geometry.XbimSolid..ctor(IIfcRevolvedAreaSolid solid, ILogger logger)
   at Xbim.Geometry.XbimGeometryCreator.CreateSolid(IIfcRevolvedAreaSolid ifcSolid, ILogger logger)
   at Xbim.Geometry.XbimGeometryCreator.Create(IIfcGeometricRepresentationItem geomRep, IIfcAxis2Placement3D objectLocation, ILogger logger)
   at Xbim.Geometry.Engine.Interop.XbimGeometryEngine.Create(IIfcGeometricRepresentationItem ifcRepresentation, ILogger logger)
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.<>c__DisplayClass39_0.<WriteShapeGeometries>b__0(Int32 shapeId)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
```

Seems to be because we're not supporting Normalising of 2D IFCDirections. 

E.g.
https://github.com/xBimTeam/XbimEssentials/blob/cb6bfe1440201d8bf3f9ae1922635274011dacfc/Xbim.Ifc4/GeometryResource/IfcDirectionPartial.cs#L87

@SteveLockley may know why

**Comment by CBenghi** [comment]
Hi all,
I've had a look at the code and I think that it makes sense for the normalisation function to work with fewer than 3 directions, since this makes no change to the original information and the API is explicitly requiring a 3D formatted object.
I've pushed an update to Essentials and will look into any related Geometry needs in the coming days.

**Comment by CBenghi** [comment]
I've fixed this issue in the develop branch.
See a6b057ff57a827a7c292c9c0beeb72f577a85eda

Best,
Claudio
