### ISSUE TITLE
Exception creating Model Context

### ISSUE THREAD

**Issue by hsbBill** [xBimTeam/XbimGeometry#269]
Attached model gives an exception when creating the model context. This model does load into a earlier version of xBim Viewer using version 4 assemblies and it's loading into other IFC viewers like Solibri etc.
 
Can you confirm if this an issue? Maybe there's some wrong in the IFC definition that causes the context to fail.
Thanks very much.

Kind regards
Bill Malcolm

Used assemblies 
Xbim.Common.dll				5.01.289.0
Xbim.Geometry.Engine.Interop.dll	5.01.317.0
Xbim.Geometry.Engine64.dll		5.01.317.0
Xbim.Ifc.dll					5.01.289.0
Xbim.Ifc2x3.dll					5.01.289.0
Xbim.Ifc4.dll					5.01.289.0
Xbim.IO.MemoryModel.dll		5.01.289.0
Xbim.ModelGeometry.Scene.dll	5.01.317.0
Xbim.Tessellator.dll				5.01.289.0

Stack Trace
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.WriteShapeGeometries(XbimCreateContextHelper contextHelper, ReportProgressDelegate progDelegate, IGeometryStoreInitialiser geometryStore, XbimGeometryType geomStorageType)

[ModelContextError.zip](https://github.com/xBimTeam/XbimGeometry/files/4964782/ModelContextError.zip)

**Comment by andyward** [comment]
Still an issue in 5.1.346. It processes gracefully but with an error logged:

```
Processing failure
General Error Creating IfcExtrudedAreaSolid, #9774
   at Xbim.Geometry.XbimGeometryCreator.Create(IIfcGeometricRepresentationItem geomRep, IIfcAxis2Placement3D objectLocation, ILogger logger)
   at Xbim.Geometry.Engine.Interop.XbimGeometryEngine.Create(IIfcGeometricRepresentationItem ifcRepresentation, ILogger logger)
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.<>c__DisplayClass39_0.<WriteShapeGeometries>b__0(Int32 shapeId)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
```
