### ISSUE TITLE
Version upgraded to 5.1.402: Xbim.Geometry.Engine64.dll could not be found.

### ISSUE THREAD

**Issue by RespectableRuessel** [xBimTeam/XbimGeometry#297]
Hi, I'm doing a development build of the Xbim.GLTF.IO library but after I upgraded to the new Xbim.Geometry version that Xbim.GLTF.IO  requires the program doesn't compile anymore.
 
`System.IO.FileLoadException: Failed to load Xbim.Geometry.Engine64.dll ---> System.IO.FileNotFoundException: Could not load file or assembly 'Xbim.Geometry.Engine.dll' or one of its dependencies. The specified module could not be found.`

My problem is that I didn't change the structure of the project at all (see below).
Both the `Xbim.Geometry.Engine32.dll` and the `Xbim.Geometry.Engine64.dll` are copied to my executable directory.
The compilation steps are the same and the csproj hasn't changed (except for the version bumps).

#### Assemblies and versions affected:
`Xbim.Geometry 5.1.402-develop`

#### Steps (or code) to reproduce the issue:
Here is my old csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net47</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ILLink.Tasks" Version="0.1.5-preview-1841731" />
    <PackageReference Include="Xbim.Essentials" Version="5.1.297" />
    <PackageReference Include="Xbim.Geometry" Version="5.1.328" />
    <PackageReference Include="Xbim.Gltf.IO" Version="4.0.1-V0007" />
  </ItemGroup>
</Project>
```

And this is my new csproj (with NET 4.7.2):
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ILLink.Tasks" Version="0.1.5-preview-1841731" />
    <PackageReference Include="Xbim.Essentials" Version="5.1.323" />
    <PackageReference Include="Xbim.Geometry" Version="5.1.402-develop" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XbimGltf\Xbim.GLTF.IO\Xbim.GLTF.IO.csproj" />
  </ItemGroup>
</Project>
```

Compiled with:
`dotnet build -c Release -r win-x64`

#### Actual behavior or exception details:
This is the complete exception:
```
System.IO.FileLoadException: Failed to load Xbim.Geometry.Engine64.dll ---> System.IO.FileNotFoundException: could not be found.
File name: 'Xbim.Geometry.Engine.dll' ---> System.IO.FileNotFoundException: Could not load file or assembly 
File name: 'Xbim.Geometry.Engine64.dll'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecutFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblyeNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byt, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
oolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Xbim.Geometry.Engine.Interop.XbimGeometryEngine..ctor(ILogger`1 logger)


   at Xbim.Geometry.Engine.Interop.XbimGeometryEngine..ctor(ILogger`1 logger)
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.get_Engine()
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.CreateContext(ReportProgressDelegate progDelegate, Boolean adjustWcs)
   at IfcToGltf.Program.Main(String[] args) in C:\Users\PC\Documents\SimpleVR\IfcToGltf\src\Program.cs:line 48
```
My output directory:
<details>
<summary>File Structure</summary>

![xbimgeo](https://user-images.githubusercontent.com/22171452/103952123-1fe83300-5140-11eb-9efe-4598ea32cbae.PNG)
</details>

#### Related:
Because I found multiple similar issues on the issue tracker I looked into the solutions provided there.
None of these actually have the same problem because my executable compiles just fine and all DLL's are getting copied to the executable location.

**Comment by RespectableRuessel** [comment]
I looked into issue #218 which states that I need to
> Create & target a Platform configuration for x86 or x64 in your solution and it will only copy the correct Geometry DLL.

Strangely it compiled just fine before . So I tried to compile with
`dotnet build -c Release -p:Platform=x64` but it doesn't work too.

**Comment by Tpullmann** [comment]
Did you check the c++ Runtime library? Do you have the latest installed?
https://support.microsoft.com/de-de/help/2977003/the-latest-supported-visual-c-downloads

**Comment by RespectableRuessel** [comment]
> 
> 
> Did you check the c++ Runtime library? Do you have the latest installed?
> https://support.microsoft.com/de-de/help/2977003/the-latest-supported-visual-c-downloads

Thanks. It looks like the required c++ runtime collides with the old one that was used before the upgrade.
I uninstalled the old runtime frameworks and did a complete reinstall. Now it works.
Thanks again!
