### ISSUE TITLE
Context Creation Failing

### ISSUE THREAD

**Issue by urosjovanovic** [xBimTeam/XbimGeometry#38]
Greetings team,

I'm having difficulties opening the submitted IFC file. Xbim is failing at geometry context creation. Tried with newest Xbim Windows UI version (master and develop).

Any help appreciated.
Best regards,
Uros

![image](https://cloud.githubusercontent.com/assets/5221157/23303478/a9674730-fa94-11e6-8e2a-df31e3591d52.png)

[140056.zip](https://github.com/xBimTeam/XbimGeometry/files/799250/140056.zip)

**Comment by urosjovanovic** [comment]
I took a closer look into it, it seems like there is no IfcGeometricRepresentationContext in file. Manually adding the entries solved the issue. In order to get models to actually show in viewer, their representations must be linked to added context.

Is there a possibility that context-less files default to 3D model context? The file opens fine in Revit, Navis and Solibri.

**Comment by ravigarg1** [comment]
Hi, If it is leading you to Create Context related error, you can try to convert the file on 64 bit machine.  We have faced this issue couple of times on a 32 bit Machine.

**Comment by urosjovanovic** [comment]
This was tested on 64 bit machine. Not really sure what do you mean by "converting" the file?

**Comment by CBenghi** [comment]
Your proposal sounds interesting, I'll see if it makes sense talking to @SteveLockley.

**Comment by theextremeandy** [comment]
Hi, I have a similar error into XBIM.Exchange program.cs at line context.CreateContext();
Have you any idea?
tnks
andrea
This is the complete exception:
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.WriteProductShape(XbimCreateContextHelper contextHelper, IIfcProduct element, Boolean includesOpenings, IGeometryStoreInitialiser txn) in c:\BuildAgent\work\860c3b913b6c647f\Xbim.ModelGeometry.Scene\Xbim3DModelContext.cs:line 980
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.<>c__DisplayClass13.<WriteFeatureElements>b__f(IGrouping`2 pair) in c:\BuildAgent\work\860c3b913b6c647f\Xbim.ModelGeometry.Scene\Xbim3DModelContext.cs:line 740
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.WriteFeatureElements(XbimCreateContextHelper contextHelper, ReportProgressDelegate progDelegate, XbimGeometryType geomType, IGeometryStoreInitialiser txn) in c:\BuildAgent\work\860c3b913b6c647f\Xbim.ModelGeometry.Scene\Xbim3DModelContext.cs:line 782
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.CreateContext(ReportProgressDelegate progDelegate, Boolean adjustWcs) in c:\BuildAgent\work\860c3b913b6c647f\Xbim.ModelGeometry.Scene\Xbim3DModelContext.cs:line 681
   at Xbim.Exchange.Program.Main(String[] args) in C:\Users\Administrator\Downloads\XbimExchange-master\XbimExchange-master\Xbim.Exchange\Program.cs:line 48
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.WriteProductShape(XbimCreateContextHelper contextHelper, IIfcProduct element, Boolean includesOpenings, IGeometryStoreInitialiser txn) in c:\BuildAgent\work\860c3b913b6c647f\Xbim.ModelGeometry.Scene\Xbim3DModelContext.cs:line 980
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.<>c__DisplayClass13.<WriteFeatureElements>b__f(IGrouping`2 pair) in c:\BuildAgent\work\860c3b913b6c647f\Xbim.ModelGeometry.Scene\Xbim3DModelContext.cs:line 740
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

**Comment by CBenghi** [comment]
Hello @theextremeandy,
can you share (in private if needed) the offending file?
Claudio

**Comment by theextremeandy** [comment]
Hello  @CBenghi 
yes I can. i sent the ifc file to your email 
tnks ;-)

**Comment by CBenghi** [comment]
@theextremeandy 
Your file seems to open without issues in the latest develop branch...
Is that the one you are using?
![image](https://user-images.githubusercontent.com/5476273/34132869-bd50a6ca-e449-11e7-839a-60da5b10b8a7.png)

**Comment by theextremeandy** [comment]
good new!
but my error occurs in phase of conversion from IFC to wexBim

**Comment by CBenghi** [comment]
Your error occurs at context creation, which is the operation needed to
open the file in Xplorer...
Have you tried with latest develop?

**Comment by theextremeandy** [comment]
I think yes
we download the entire project in zip format
and we upgrade with NuGet
so we are using XbimEssentials version V4.0.29
is this correct?

**Comment by theextremeandy** [comment]
another problem is below
steps:
download XbimWindowsUI
open project with VS2017
build ok
add packages sources Develop and Master to NuGet pakage manager setting
build ok
update log4net
build ok
update json
build ok
update essentials
build with errors in attached image
![screen shot 12-20-17 at 10 53 am](https://user-images.githubusercontent.com/18160434/34201246-2c753fea-e574-11e7-8a49-e22ee1f19532.PNG)
the second one I think is simple resolve without the last parameter
but we can't resolve this:
pe.Activate(false);
can you help me
tnks

**Comment by CBenghi** [comment]
I see from the screenshot that you are not under a git repo ("add to source control")....
Can you try again through git and checking out develop branch?
I think your problem is there.
Claudio

**Comment by SteveLockley** [comment]
Files that contain no geometric representation context are possible but violate the Ifc schema. The context gives information on precision and coordinate systems. If precision is not correctly specified boolean operations can often fail. It is better to have a valid ifc file rather than default to some "typical" precision. 
I am closing this issue as the failure to create a context is resolved in the latest versions
