### ISSUE TITLE
System.OutOfMemoryException. Array dimensions exceeded supported range.

### ISSUE THREAD

**Issue by Blogbotana** [xBimTeam/XbimGeometry#477]
Hello. I am using engine version 5.1.437 and trying to open a file that is over 4.5 GB. It gives the following error:

at System.Collections.Generic.Dictionary`2.Initialize(Int32 capacity)
   at System.Collections.Generic.Dictionary`2..ctor(Int32 capacity, IEqualityComparer`1 comparer)
   at Xbim.IO.Step21.XbimP21Scanner..ctor(Stream strm, Int64 streamSize, IEnumerable`1 ignoreTypes) in D:\a\1\s\Xbim.Common\Step21\XbimP21Scanner.cs:line 115
   at Xbim.Common.Model.StepModel.LoadStep21(Stream stream, Int64 streamSize, ReportProgressDelegate progDelegate, IEnumerable`1 ignoreTypes) in D:\a\1\s\Xbim.Common\Model\StepModel.cs:line 555
   at Xbim.Common.Model.StepModel.LoadStep21(String file, ReportProgressDelegate progDelegate) in D:\a\1\s\Xbim.Common\Model\StepModel.cs:line 584
   at Xbim.IO.Memory.MemoryModelProvider.Open(String path, XbimSchemaVersion schemaVersion, Nullable`1 ifcDatabaseSizeThreshHold, ReportProgressDelegate progDelegate, XbimDBAccess accessMode, Int32 codePageOverride) in D:\a\1\s\Xbim.IO.MemoryModel\MemoryModelProvider.cs:line 111
   at Xbim.Ifc.IfcStore.Open(String path, XbimEditorCredentials editorDetails, Nullable`1 ifcDatabaseSizeThreshHold, ReportProgressDelegate progDelegate, XbimDBAccess accessMode, Int32 codePageOverride) in D:\a\1\s\Xbim.Ifc\IfcStore.cs:line 251

How can I try to open a large file?

I use IfcStore.Open(); method

**Comment by andyward** [comment]
Are you definitely using a 64bit process? 

It looks like you're using the `MemoryModel` which holds the entire structure in RAM and will need way more than 4.5GB. It looks like you are not calling:

```csharp
IfcStore.ModelProviderFactory.UseHeuristicModelProvider();
```
in the application start as per the [Readme](https://github.com/xBimTeam/XbimEssentials/tree/ac8b9092b87ae401d91d53578388b2b746c26852?tab=readme-ov-file#updating-from-prior-versions)
... which brings in the `EsentModel` for larger models, and should reduce memory footprint.

**Comment by Blogbotana** [comment]
![image](https://github.com/xBimTeam/XbimGeometry/assets/69924139/6de48fd0-4d80-4ec4-b879-629afa7aa4c8)
I tried to call your method, but it was not found. I'm using version 5.1

**Comment by Blogbotana** [comment]
![image](https://github.com/xBimTeam/XbimGeometry/assets/69924139/7fa12afc-f2f2-4de9-a34a-9ebb7b859cc7)
I've updated all libs and now I can't use new way. 
![image](https://github.com/xBimTeam/XbimGeometry/assets/69924139/c6cf9286-0407-4f62-85e3-4b592fddd37e)

**Comment by andyward** [comment]
Looks like you are missing a reference to `Xbim.IO.Esent` package? If you reference Xbim.Essentials it should bring it in automatically. See https://github.com/xBimTeam/XbimEssentials/blob/4ed33f7a0427ea91bc7825810c381779ecf5053c/Xbim.IO.Esent/EsentModelProviderExtensions.cs#L19

**Comment by Blogbotana** [comment]
Thank you. You solved my problem
