### ISSUE TITLE
Multi-Threading Crash (AccessViolationException)

### ISSUE THREAD

**Issue by WalchAndreas** [xBimTeam/XbimGeometry#489]
While loading Ifc-projects, an AccessViolationException is thrown (often), but investigations conclude it is a multi-threading issue. 

#### Assemblies and versions affected:

official nuget-packages:
- Xbim.Common (6.0.445)
- Xbim.Essentials (6.0.445)
- Xbim.Ifc (6.0.445)
- Xbim.Ifc2x3 (6.0.445)
- Xbim.Ifc4 (6.0.445)
- Xbim.Ifc4x3 (6.0.445)
- Xbim.IO.Esent (6.0.445)
- Xbim.IO.MemoryModel (6.0.445)
- Xbim.Tessellator (6.0.445)

local nuget-packages from source (branch feature/netcore)
- Xbim.Geometry (6.0.0-dev)
- Xbim.Geometry.Engine.Interop (6.0.0-dev)
- Xbim.ModelGeometry.Scene (6.0.0-dev)

remote: https://www.myget.org/F/xbim-develop/api/v3/index.json
- Xbim.Geometry.Abstractions (6.2.346-develop)
      - Xbim.Essentials (>= 6.0.414-develop)

#### Stacktrace

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at <Module>.BRepBuilderAPI_MakeEdge2d.{ctor}(BRepBuilderAPI_MakeEdge2d*, opencascade.handle<Geom2d_Curve>*)
--------------------------------
   at <Module>.NWireFactory.BuildWire(NWireFactory*, TopoDS_Wire*, NCollection_Sequence<opencascade::handle<Geom2d_BoundedCurve> >*, Double, Double)
   at Xbim.Geometry.Factories.WireFactory.BuildWire(TopoDS_Wire*, Xbim.Ifc4.Interfaces.IIfcIndexedPolyCurve, Boolean)
   at Xbim.Geometry.Factories.WireFactory.BuildWire(TopoDS_Wire*, Xbim.Ifc4.Interfaces.IIfcCurve, Boolean)
   at Xbim.Geometry.Factories.ProfileFactory.BuildProfileWire(TopoDS_Wire*, Xbim.Ifc4.Interfaces.IIfcArbitraryClosedProfileDef)
   at Xbim.Geometry.Factories.ProfileFactory.BuildProfileFace(TopoDS_Face*, Xbim.Ifc4.Interfaces.IIfcArbitraryClosedProfileDef)
   at Xbim.Geometry.Factories.ProfileFactory.BuildProfileFace(TopoDS_Face*, Xbim.Ifc4.Interfaces.IIfcProfileDef)
   at Xbim.Geometry.Factories.SolidFactory.BuildExtrudedAreaSolid(TopoDS_Shape*, Xbim.Ifc4.Interfaces.IIfcExtrudedAreaSolid, Xbim.Ifc4.Interfaces.IIfcProfileDef)
   at Xbim.Geometry.XbimSolid.Init(Xbim.Ifc4.Interfaces.IIfcExtrudedAreaSolid, Xbim.Ifc4.Interfaces.IIfcProfileDef, Microsoft.Extensions.Logging.ILogger)
   at Xbim.Geometry.XbimSolid.Init(Xbim.Ifc4.Interfaces.IIfcSweptAreaSolid, Xbim.Ifc4.Interfaces.IIfcProfileDef, Microsoft.Extensions.Logging.ILogger)
   at Xbim.Geometry.XbimSolid.Init(Xbim.Ifc4.Interfaces.IIfcSolidModel, Microsoft.Extensions.Logging.ILogger)
   at Xbim.Geometry.XbimSolid..ctor(Xbim.Ifc4.Interfaces.IIfcSweptAreaSolid, Microsoft.Extensions.Logging.ILogger, Xbim.Geometry.Services.ModelGeometryService)
   at Xbim.Geometry.XbimGeometryCreator.CreateSolid(Xbim.Ifc4.Interfaces.IIfcExtrudedAreaSolid, Microsoft.Extensions.Logging.ILogger)
   at Xbim.Geometry.XbimGeometryCreator.CreateSolid(Xbim.Ifc4.Interfaces.IIfcSweptAreaSolid, Microsoft.Extensions.Logging.ILogger)
   at Xbim.Geometry.XbimGeometryCreator.Create(Xbim.Ifc4.Interfaces.IIfcGeometricRepresentationItem, Xbim.Ifc4.Interfaces.IIfcAxis2Placement3D, Microsoft.Extensions.Logging.ILogger)
   at Xbim.Geometry.XbimGeometryCreator.Create(Xbim.Ifc4.Interfaces.IIfcGeometricRepresentationItem, Microsoft.Extensions.Logging.ILogger)
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext+<>c__DisplayClass44_0.<WriteShapeGeometries>b__0(Int32)
   at System.Threading.Tasks.Parallel+<>c__DisplayClass43_0`2[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<PartitionerForEachWorker>b__1(System.Collections.IEnumerator ByRef, Int64, Boolean ByRef)
   at System.Threading.Tasks.TaskReplicator+Replica.Execute()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
```

#### Minimal file to reproduce the issue:
Loading the [Minimal Test Project](https://github.com/user-attachments/files/16161910/multi_thread_issue.zip) crashes (very often) in a multi threading (standard) environment.

```
var model = IfcStore.Open(filePath, editor);

// enable caching - we only load once and do not change the project
model.BeginInverseCaching(); 
model.BeginEntityCaching();

if (model.GeometryStore.IsEmpty)
{
    var context = new Xbim3DModelContext(model);
    //upgrade to new geometry representation, uses the default 3D model
    context.CreateContext(null, true, false);
}
```

#### Workaround - Single Threading

Enforce single threading by setting **Xbim3DModelContext.MaxThreads = 1**.

```
var context = new Xbim3DModelContext(model);
context.MaxThreads = 1; // <--------------------------USE THIS TO ENFORCE SINGLE-THREADING
context.CreateContext(null, true, false);
```

**Comment by rainer-helbing** [comment]
I had a AccessViolationException running `Xbim3DModelContext.CreateContext` on a virtual machine. The stack trace was
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory.
This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at <Module>._Mtx_lock(_Mtx_internal_imp_t*)
--------------------------------
   at <Module>.std._Mutex_base.lock(std._Mutex_base*)
   at <Module>.Cache.Clear(Cache*)
   at ManagedCache.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalRelease(Boolean)
   at System.Runtime.InteropServices.SafeHandle.Finalize()
```
I use a Xbim.Geometry.Engine forked from `XbimGeometry_netcore_6.1.801`.

After reading the answers in [Why is std::mutex so much worse than std::shared_mutex in Visual C++?](https://stackoverflow.com/questions/69990339/why-is-stdmutex-so-much-worse-than-stdshared-mutex-in-visual-c) I suspect that the C++ runtime library versions used in OPEN CASCADE (i.e. Xbim.Geometry.Occt 7.7.0-beta) and in my build of Xbim.Geometry.Engine (Visual Studio 2022 17.14.8) are not compatible.  
There is also an issue on [MS Developer Comunity](https://developercommunity.visualstudio.com/t/Access-violation-with-std::mutex::lock-a/10664660).

As a test I replaced `std::mutex` by `std::shared_mutex` in the file _Cache.h_ and the error disappeared.

**Comment by andyward** [comment]
Interesting - this possibly points at incompatibility in the VC140 runtime versions. It would be useful to know the
 version of VC140 you have installed. Is this occurring on your developed machine or a user's (where you'd expect the runtime to need deploying)?

Were you able to run the tests with the `std::shared_mutex` change and see no regressions? Happy to take a PR if you can show no regression.

Also interested to see if the __DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR_ macro has any impact - mentioned the the 2nd link

BTW My understanding is that an old lib can be used with a newer VC140 runtime but not vice versa. So even if Occt.7.7.0 is built against an runtime it should be fine linked with a newer one.

**Comment by rainer-helbing** [comment]
> Were you able to run the tests with the std::shared_mutex change and see no regressions? Happy to take a PR if you can show no regression.

I ran all test cases in _Xbim.Geometry.Engine.sln_ and they give the same result with or without `std::shared_mutex`
|  | debug config | release config |
| --- | --- | --- |
| std::mutex | 418 tests, 413 succeded, 5 skipped | 418 tests, 412 succeded, 1 failed, 5 skipped |
| std::shared_mutex | 418 tests, 413 succeded, 5 skipped | 418 tests, 412 succeded, 1 failed, 5 skipped |

The failing test in the release configuration is _IfcExtrudedAreaSolidInvalidPlacementTest_

I will submit the pull request.

**Comment by andyward** [comment]
Thanks for this PR @rainer-helbing - should be merged now, and packages in Myget

Will pick up the failing test separately
